UPDATE abilities SET CE = 2800 WHERE name = 'invincible';
UPDATE abilities SET recastTime = 120 WHERE name = 'warcry';
UPDATE abilities SET CE = 200 WHERE name = 'provoke';
UPDATE abilities SET recastTime = 60 WHERE name = 'steal';
UPDATE abilities SET recastTime = 60 WHERE name = 'hide';
UPDATE abilities SET recastTime = 60 WHERE name = 'mug';
UPDATE abilities SET recastTime = 60, CE = 200 WHERE name = 'shield_bash';
UPDATE abilities SET CE = 100 WHERE name = 'sentinel';
UPDATE abilities SET VE = 600 WHERE name = 'souleater';
UPDATE abilities SET VE = 600 WHERE name = 'last_resort';
UPDATE abilities SET recastTime = 60 WHERE name = 'shadowbind';
UPDATE abilities SET recastTime = 300 WHERE name = 'call_wyvern';
UPDATE abilities SET recastTime = 60 WHERE name = 'jump';
UPDATE abilities SET recastTime = 120 WHERE name = 'high_jump';
UPDATE abilities SET recastTime = 300 WHERE name = 'divine_seal';
UPDATE abilities SET recastTime = 300 WHERE name = 'elemental_seal';
UPDATE abilities SET CE = 100, VE = 100 WHERE name = 'cover';
UPDATE abilities SET recastTime = 120 WHERE name = 'spirit_link';
UPDATE abilities SET recastTime = 120 WHERE name = 'chi_blast';
UPDATE abilities SET recastTime = 180 WHERE name = 'accomplice';
UPDATE abilities SET recastTime = 50 WHERE name = 'blood_pact_rage';
UPDATE abilities SET CE = 100 WHERE name = 'rampart';
UPDATE abilities SET recastTime = 45 WHERE abilityId between 97 and 122; -- Corsair Rolls
UPDATE abilities SET recastTime = 600 WHERE name = 'random_deal';
UPDATE abilities SET recastTime = 2400 WHERE name = 'overdrive';
UPDATE abilities SET recastTime = 120 WHERE name = 'shikikoyo';
UPDATE abilities SET recastTime = 50 WHERE name = 'blood_pact_ward';
UPDATE abilities SET recastTime = 2400 WHERE name = 'trance';
UPDATE abilities SET recastTime = 2400 WHERE name = 'tabula_rasa';
UPDATE abilities SET recastTime = 180 WHERE name = 'sekkanoki';
UPDATE abilities SET level = 75 WHERE name = 'restraint';
UPDATE abilities SET level = 75, recastTime = 300 WHERE name = 'impetus';
UPDATE abilities SET level = 75 WHERE name = 'divine_caress';
UPDATE abilities SET level = 75 WHERE name = 'enmity_douse';
UPDATE abilities SET level = 75 WHERE name = 'saboteur';
UPDATE abilities SET level = 75 WHERE name = 'conspirator';
UPDATE abilities SET level = 75 WHERE name = 'palisade';
UPDATE abilities SET level = 75 WHERE name = 'nether_void';
UPDATE abilities SET level = 75 WHERE name = 'marcato';
UPDATE abilities SET level = 75 WHERE name = 'decoy_shot';
UPDATE abilities SET level = 75 WHERE name = 'sengikori';
UPDATE abilities SET level = 75 WHERE name = 'issekigan';
UPDATE abilities SET level = 75 WHERE name = 'spirit_jump';
UPDATE abilities SET level = 75 WHERE name = 'efflux';
UPDATE abilities SET level = 75 WHERE name = 'crooked_cards';
UPDATE abilities SET level = 75 WHERE name = 'tactical_switch';
UPDATE abilities SET level = 75 WHERE name = 'presto';
UPDATE abilities SET level = 75 WHERE name = 'libra';
UPDATE abilities SET level = 75 WHERE name = 'One_for_all';
UPDATE abilities SET recastTime = 120 WHERE name = 'unlimited_shot';
UPDATE abilities SET recastTime = 220 WHERE name = 'sharpshot';
UPDATE abilities SET isAOE = 1 WHERE name = 'divine_waltz_ii';
UPDATE abilities SET `range` = 12 WHERE abilityId IN (98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,302,303,304,305,390,391); -- cor rolls 12 range
UPDATE abilities SET level = 50 WHERE name = 'retaliation';
UPDATE abilities SET recastTime = 60 WHERE abilityId = 170; -- angon
UPDATE abilities SET recastTime = 5 WHERE abilityId = 229; -- pianissimo
UPDATE abilities SET recastTime = 600 WHERE name = 'diffusion';
UPDATE abilities SET recastTime = 600 WHERE name = 'warriors_charge';
UPDATE abilities SET recastTime = 600 WHERE name = 'martyr';
UPDATE abilities SET recastTime = 600 WHERE name = 'devotion';
UPDATE abilities SET recastTime = 600 WHERE name = 'assassins_charge';
UPDATE abilities SET recastTime = 600 WHERE name = 'feint';
UPDATE abilities SET recastTime = 600 WHERE name = 'fealty';
UPDATE abilities SET recastTime = 600 WHERE name = 'chivalry';
UPDATE abilities SET recastTime = 600 WHERE name = 'dark_seal';
UPDATE abilities SET recastTime = 600 WHERE name = 'diabolic_eye';
UPDATE abilities SET recastTime = 600 WHERE name = 'feral_howl';
UPDATE abilities SET recastTime = 600 WHERE name = 'killer_instinct';
UPDATE abilities SET recastTime = 600 WHERE name = 'nightingale';
UPDATE abilities SET recastTime = 600 WHERE name = 'troubadour';
UPDATE abilities SET recastTime = 600 WHERE name = 'flashy_shot';
UPDATE abilities SET recastTime = 600 WHERE name = 'blade_bash';
UPDATE abilities SET recastTime = 600 WHERE name = 'deep_breathing';
UPDATE abilities SET recastTime = 600 WHERE name = 'sange';
UPDATE abilities SET recastTime = 600 WHERE name = 'diffusion';
UPDATE abilities SET recastTime = 600 WHERE name = 'snake_eye';
UPDATE abilities SET recastTime = 600 WHERE name = 'fold';

UPDATE abilities SET content_tag = NULL;